workflows:
  ios-workflow:
    name: iOS Build
    working_directory: frontend
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release
